import { prisma } from "./prisma";
import type { Prisma } from "@prisma/client";

export const dailyRecordInclude = {
  productionLines: { include: { packer: true } },
  driverSales: { include: { driver: true, customer: true } },
  truckDeliveries: { include: { customer: true } },
  expenseItems: { include: { paidBy: true } },
  factoryCustomer: true,
  createdBy: true,
  approvedBy: true,
  archivedBy: true,
} satisfies Prisma.DailyRecordInclude;

export type DailyRecordFull = Prisma.DailyRecordGetPayload<{
  include: typeof dailyRecordInclude;
}>;

/** Active (not archived) records only — this is "the current recording session" everywhere it's used. */
export async function getAllRecordsSorted(): Promise<DailyRecordFull[]> {
  return prisma.dailyRecord.findMany({
    where: { archivedAt: null },
    include: dailyRecordInclude,
    orderBy: { date: "desc" },
  });
}

/** Active (not archived) approved records — used for stock chain, dashboard, and weekly incentive progress. */
export async function getApprovedRecordsSorted(): Promise<DailyRecordFull[]> {
  const records = await prisma.dailyRecord.findMany({
    where: { status: "APPROVED", archivedAt: null },
    include: dailyRecordInclude,
    orderBy: { date: "asc" },
  });
  return records;
}

/**
 * Approved records regardless of archive state — used only where history must
 * keep counting straight through an archive, e.g. yearly incentive totals
 * (a customer/driver's business relationship doesn't reset just because the
 * books did).
 */
export async function getAllApprovedRecordsEverSorted(): Promise<DailyRecordFull[]> {
  const records = await prisma.dailyRecord.findMany({
    where: { status: "APPROVED" },
    include: dailyRecordInclude,
    orderBy: { date: "asc" },
  });
  return records;
}

/** Archived records only, most recently archived first — for the Archive History view. */
export async function getArchivedRecordsSorted(): Promise<DailyRecordFull[]> {
  return prisma.dailyRecord.findMany({
    where: { archivedAt: { not: null } },
    include: dailyRecordInclude,
    orderBy: [{ archivedAt: "desc" }, { date: "desc" }],
  });
}

export function recordProdTotal(r: DailyRecordFull): number {
  return r.productionLines.reduce((s, p) => s + p.bags, 0);
}

export function recordDriverBagsTotal(r: DailyRecordFull): number {
  return r.driverSales.reduce((s, d) => s + d.bags, 0);
}

export function recordDriverBonusBagsTotal(r: DailyRecordFull): number {
  return r.driverSales.reduce((s, d) => s + d.bonusBags, 0);
}

export function recordTruckDeliveryBagsTotal(r: DailyRecordFull): number {
  return r.truckDeliveries.reduce((s, t) => s + t.bags, 0);
}

export function recordTruckDeliveryBonusBagsTotal(r: DailyRecordFull): number {
  return r.truckDeliveries.reduce((s, t) => s + t.bonusBags, 0);
}

export function recordSoldTotal(r: DailyRecordFull): number {
  return r.factoryBags + recordDriverBagsTotal(r) + recordTruckDeliveryBagsTotal(r);
}

export function recordExpenseTotal(r: DailyRecordFull): number {
  return r.expenseItems.reduce((s, e) => s + e.amount, 0);
}

/** Packer pay is no longer an ExpenseItem (see PackerPayment) — derived straight from that day's production. */
export function recordPackerPayTotal(r: DailyRecordFull): number {
  return r.productionLines.reduce((s, p) => s + p.bags * p.pricePerBag, 0);
}

/** Logged expense items plus that day's packer pay — the true cost total for revenue/reporting purposes. */
export function recordTotalCosts(r: DailyRecordFull): number {
  return recordExpenseTotal(r) + recordPackerPayTotal(r);
}

/**
 * "Loading fee — X" expense lines are regenerated fresh from driverSales/
 * production on every create or update — never carry them into an editable
 * expense list as if they were manual entries, or they'll be duplicated
 * (the carried-over copy plus the freshly regenerated one). "Packer pay — "
 * is kept here even though nothing creates new rows with that prefix any
 * more (packer pay is now a running balance — see PackerPayment) so any
 * leftover legacy row from before that switch still gets excluded here
 * rather than leaking into the editable expense list.
 */
const AUTO_GENERATED_EXPENSE_PREFIXES = [
  "Loading fee — ",
  "Packer pay — ",
  "Truck fuel — ",
  "Hired truck — ",
  "Offloading fee — ",
];
export function isAutoGeneratedExpense(description: string): boolean {
  return AUTO_GENERATED_EXPENSE_PREFIXES.some((prefix) => description.startsWith(prefix));
}

/** Matches the "Rolls" expense line specifically (not "Rolls" as a substring of something else). */
export function isRollsExpense(description: string): boolean {
  return description.trim().toLowerCase() === "rolls";
}

/** Matches the "Packing bags" expense line specifically. */
export function isPackingBagsExpense(description: string): boolean {
  return description.trim().toLowerCase() === "packing bags";
}

export function expenseStatusSuffix(e: { amount: number; amountPaid: number; paid: boolean }): string {
  if (e.paid) return "";
  return e.amountPaid > 0 ? " (partially paid)" : " (unpaid)";
}
