import { prisma } from "./prisma";
import type { Prisma } from "@prisma/client";

export const dailyRecordInclude = {
  productionLines: { include: { packer: true } },
  driverSales: { include: { driver: true, customer: true } },
  truckDeliveries: { include: { customer: true } },
  expenseItems: { include: { paidBy: true } },
  factoryCustomer: true,
  createdBy: true,
  approvedBy: true,
} satisfies Prisma.DailyRecordInclude;

export type DailyRecordFull = Prisma.DailyRecordGetPayload<{
  include: typeof dailyRecordInclude;
}>;

export async function getAllRecordsSorted(): Promise<DailyRecordFull[]> {
  return prisma.dailyRecord.findMany({
    include: dailyRecordInclude,
    orderBy: { date: "desc" },
  });
}

export async function getApprovedRecordsSorted(): Promise<DailyRecordFull[]> {
  const records = await prisma.dailyRecord.findMany({
    where: { status: "APPROVED" },
    include: dailyRecordInclude,
    orderBy: { date: "asc" },
  });
  return records;
}

export function recordProdTotal(r: DailyRecordFull): number {
  return r.productionLines.reduce((s, p) => s + p.bags, 0);
}

export function recordDriverBagsTotal(r: DailyRecordFull): number {
  return r.driverSales.reduce((s, d) => s + d.bags, 0);
}

export function recordDriverBonusBagsTotal(r: DailyRecordFull): number {
  return r.driverSales.reduce((s, d) => s + d.bonusBags, 0);
}

export function recordTruckDeliveryBagsTotal(r: DailyRecordFull): number {
  return r.truckDeliveries.reduce((s, t) => s + t.bags, 0);
}

export function recordTruckDeliveryBonusBagsTotal(r: DailyRecordFull): number {
  return r.truckDeliveries.reduce((s, t) => s + t.bonusBags, 0);
}

export function recordSoldTotal(r: DailyRecordFull): number {
  return r.factoryBags + recordDriverBagsTotal(r) + recordTruckDeliveryBagsTotal(r);
}

export function recordExpenseTotal(r: DailyRecordFull): number {
  return r.expenseItems.reduce((s, e) => s + e.amount, 0);
}

/**
 * "Loading fee — X" and "Packer pay — X" expense lines are regenerated fresh
 * from driverSales/production on every create or update — never carry them
 * into an editable expense list as if they were manual entries, or they'll
 * be duplicated (the carried-over copy plus the freshly regenerated one).
 */
const AUTO_GENERATED_EXPENSE_PREFIXES = [
  "Loading fee — ",
  "Packer pay — ",
  "Truck fuel — ",
  "Hired truck — ",
  "Offloading fee — ",
];
export function isAutoGeneratedExpense(description: string): boolean {
  return AUTO_GENERATED_EXPENSE_PREFIXES.some((prefix) => description.startsWith(prefix));
}

/**
 * Maps packerId -> whether that packer's "Packer pay — X" expense line was
 * marked paid, so a production row's paid/owing state survives round-tripping
 * back into an editable form (auto-fill on date match, edit modal, quick-add
 * merge). Packer pay expenses are the only ones with a packerId set.
 */
export function packerPaidMap(expenseItems: { packerId: string | null; paid: boolean }[]): Map<string, boolean> {
  const map = new Map<string, boolean>();
  for (const e of expenseItems) {
    if (e.packerId) map.set(e.packerId, e.paid);
  }
  return map;
}
