"use server";

import { revalidatePath } from "next/cache";
import { after } from "next/server";
import { Prisma } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { requireRole, requireUser } from "@/lib/auth-helpers";
import { needsApproval, isApprover } from "@/lib/roles";
import { logActivity } from "@/lib/activity";
import { notifyDailyRecordApprovers, sendPushToUsers } from "@/lib/push";
import { dailyRecordSchema, dailyRecordEditSchema } from "@/lib/validation/daily-record";
import { latestClosingStock, latestLeakageClosing, computeClosingStock, computeLeakageClosing } from "@/lib/stock";
import { getPricingSettings } from "@/lib/settings";
import {
  dailyRecordInclude,
  recordProdTotal,
  recordDriverBagsTotal,
  recordDriverBonusBagsTotal,
  recordTruckDeliveryBagsTotal,
  recordTruckDeliveryBonusBagsTotal,
  isAutoGeneratedExpense,
  packerPaidMap,
} from "@/lib/records";

function buildLoadingFeeExpenses(
  driverSales: { driverId: string; bags: number; loadingFeeWaived: boolean }[],
  driverById: Map<string, { name: string; loadingFee: number }>
) {
  const expenses: { description: string; amount: number; paid: boolean; paidAt: null; paidById: null }[] = [];
  for (const d of driverSales) {
    if (d.bags <= 0 || d.loadingFeeWaived) continue;
    const driver = driverById.get(d.driverId);
    if (!driver || driver.loadingFee <= 0) continue;
    expenses.push({
      description: `Loading fee — ${driver.name}`,
      amount: d.bags * driver.loadingFee,
      paid: false,
      paidAt: null,
      paidById: null,
    });
  }
  return expenses;
}

/**
 * Every truck delivery's fuel cost (own truck) or hired-truck price, plus
 * its loading/offloading fee (fixed ₦/bag rates set on Settings, applying
 * regardless of own vs hired truck), is logged as its own expense line —
 * same treatment as driver loading fees — so it shows up on the Expenses
 * page and can be marked paid/owing there, instead of only being visible as
 * a field on the delivery itself.
 */
function buildTruckCostExpenses(
  truckDeliveries: {
    customerId: string;
    bags: number;
    ownTruck: boolean;
    fuelCost: number;
    hiredCost: number;
    loadingFeeWaived: boolean;
    offloadingFeeWaived: boolean;
  }[],
  customerById: Map<string, { name: string }>,
  truckLoadingFeePerBag: number,
  truckOffloadingFeePerBag: number
) {
  const expenses: { description: string; amount: number; paid: boolean; paidAt: null; paidById: null }[] = [];
  for (const t of truckDeliveries) {
    const customerName = customerById.get(t.customerId)?.name ?? "no customer";

    const cost = t.ownTruck ? t.fuelCost : t.hiredCost;
    if (cost > 0) {
      expenses.push({
        description: `${t.ownTruck ? "Truck fuel" : "Hired truck"} — ${customerName}`,
        amount: cost,
        paid: false,
        paidAt: null,
        paidById: null,
      });
    }

    if (t.bags > 0 && !t.loadingFeeWaived && truckLoadingFeePerBag > 0) {
      expenses.push({
        description: `Loading fee — ${customerName}`,
        amount: t.bags * truckLoadingFeePerBag,
        paid: false,
        paidAt: null,
        paidById: null,
      });
    }
    if (t.bags > 0 && !t.offloadingFeeWaived && truckOffloadingFeePerBag > 0) {
      expenses.push({
        description: `Offloading fee — ${customerName}`,
        amount: t.bags * truckOffloadingFeePerBag,
        paid: false,
        paidAt: null,
        paidById: null,
      });
    }
  }
  return expenses;
}

/**
 * Packers are entered as free text on the daily record form, same as before —
 * there's no separate "add packer" step. Matching an existing name (case-
 * insensitively) reuses that packer's id and history; an unrecognized name
 * creates a new Packer record on the spot. Pay is a single ₦/bag rate that
 * applies to every packer (set on Settings), not a per-packer rate.
 */
async function resolvePackers(
  names: string[],
  createdById: string
): Promise<Map<string, { id: string; name: string }>> {
  const trimmedNames = [...new Set(names.map((n) => n.trim()).filter(Boolean))];
  const result = new Map<string, { id: string; name: string }>();
  for (const name of trimmedNames) {
    const key = name.toLowerCase();
    let packer = await prisma.packer.findFirst({ where: { name: { equals: name, mode: "insensitive" } } });
    if (!packer) {
      packer = await prisma.packer.create({ data: { name, createdById } });
    }
    result.set(key, packer);
  }
  return result;
}

function buildPackerPayExpenses(
  production: { packerName: string; bags: number; paid: boolean }[],
  packerByName: Map<string, { id: string; name: string }>,
  packerPricePerBag: number,
  paidById: string
) {
  const expenses: {
    description: string;
    amount: number;
    amountPaid: number;
    paid: boolean;
    paidAt: Date | null;
    paidById: string | null;
    packerId: string;
  }[] = [];
  if (packerPricePerBag <= 0) return expenses;
  for (const p of production) {
    if (p.bags <= 0) continue;
    const packer = packerByName.get(p.packerName.trim().toLowerCase());
    if (!packer) continue;
    const amount = p.bags * packerPricePerBag;
    expenses.push({
      description: `Packer pay — ${packer.name}`,
      amount,
      amountPaid: p.paid ? amount : 0,
      paid: p.paid,
      paidAt: p.paid ? new Date() : null,
      paidById: p.paid ? paidById : null,
      packerId: packer.id,
    });
  }
  return expenses;
}

export interface CreateDailyRecordResult {
  ok: boolean;
  error?: string;
}

export async function createDailyRecord(input: unknown): Promise<CreateDailyRecordResult> {
  const user = await requireRole([
    "SALES_STAFF",
    // "EDITOR", // disabled for now
    "ADMIN_STAFF",
    "ADMIN",
    "SUPER_ADMIN",
  ]);
  const parsed = dailyRecordSchema.safeParse(input);
  if (!parsed.success) {
    return { ok: false, error: parsed.error.issues[0]?.message ?? "Invalid input" };
  }
  const data = parsed.data;

  const existing = await prisma.dailyRecord.findUnique({ where: { date: data.date } });
  if (existing) {
    return { ok: false, error: `A daily record for ${data.date} already exists.` };
  }

  const [computedOpening, computedLeakageOpening, fixedPricing, drivers, truckCustomers, packerByName] =
    await Promise.all([
      latestClosingStock(),
      latestLeakageClosing(),
      getPricingSettings(),
      prisma.driver.findMany({ where: { id: { in: data.driverSales.map((d) => d.driverId) } } }),
      prisma.customer.findMany({
        where: { id: { in: data.truckDeliveries.map((t) => t.customerId) } },
      }),
      resolvePackers(
        data.production.map((p) => p.packerName),
        user.id
      ),
    ]);

  const opening =
    user.role === "SUPER_ADMIN" && data.openingStockOverride != null ? data.openingStockOverride : computedOpening;
  const leakageOpening =
    user.role === "SUPER_ADMIN" && data.leakageOpeningOverride != null
      ? data.leakageOpeningOverride
      : computedLeakageOpening;

  if (data.factoryBagsFromLeakage + data.leakageWasteBags > leakageOpening) {
    return {
      ok: false,
      error: `Only ${leakageOpening} bags are available in the leakage pile to rebag or waste.`,
    };
  }

  const prodTotal = data.production.reduce((s, p) => s + p.bags, 0);
  const driverBagsTotal = data.driverSales.reduce((s, d) => s + d.bags, 0);
  const driverBonusBagsTotal = data.driverSales.reduce((s, d) => s + d.bonusBags, 0);
  const truckDeliveryBagsTotal = data.truckDeliveries.reduce((s, t) => s + t.bags, 0);
  const truckDeliveryBonusBagsTotal = data.truckDeliveries.reduce((s, t) => s + t.bonusBags, 0);

  const closing = computeClosingStock({
    opening,
    prodTotal,
    factoryBags: data.factoryBags,
    factoryBagsFromLeakage: data.factoryBagsFromLeakage,
    driverBagsTotal,
    driverBonusBagsTotal,
    truckDeliveryBagsTotal,
    truckDeliveryBonusBagsTotal,
    leakageBagsNew: data.leakageBags,
  });
  const leakageClosing = computeLeakageClosing(
    leakageOpening,
    data.leakageBags,
    data.factoryBagsFromLeakage,
    data.leakageWasteBags
  );
  const pending = needsApproval(user.role);

  const canEditFactoryPrice = user.role === "ADMIN" || user.role === "SUPER_ADMIN";
  const factoryPricePerBag = canEditFactoryPrice ? data.factoryPricePerBag : fixedPricing.factoryPricePerBag;
  const driverById = new Map(drivers.map((d) => [d.id, d]));
  const truckCustomerById = new Map(truckCustomers.map((c) => [c.id, c]));

  try {
    const record = await prisma.dailyRecord.create({
      data: {
        date: data.date,
        openingStock: opening,
        closingStock: closing,
        factoryBags: data.factoryBags,
        factoryBagsFromLeakage: data.factoryBagsFromLeakage,
        factoryPricePerBag,
        factoryCustomerId: data.factoryCustomerId || null,
        pumpWaterAmount: data.pumpWaterAmount,
        leakageOpening,
        leakageBags: data.leakageBags,
        leakageWasteBags: data.leakageWasteBags,
        leakageClosing,
        status: pending ? "PENDING" : "APPROVED",
        createdById: user.id,
        createdByRole: user.role,
        approvedById: pending ? null : user.id,
        productionLines: {
          create: data.production.map((p) => {
            const packer = packerByName.get(p.packerName.trim().toLowerCase());
            return { packerId: packer!.id, bags: p.bags, pricePerBag: fixedPricing.packerPricePerBag };
          }),
        },
        driverSales: {
          create: data.driverSales.map((d) => {
            const driver = driverById.get(d.driverId);
            return {
              driverId: d.driverId,
              bags: d.bags,
              pricePerBag: driver?.pricePerBag ?? 0,
              loadingFee: driver?.loadingFee ?? 0,
              loadingFeeWaived: d.loadingFeeWaived,
              bonusBags: d.bonusBags,
            };
          }),
        },
        truckDeliveries: {
          create: data.truckDeliveries.map((t) => {
            const customer = truckCustomerById.get(t.customerId);
            return {
              customerId: t.customerId,
              bags: t.bags,
              bonusBags: t.bonusBags,
              pricePerBag: customer?.pricePerBag ?? 0,
              ownTruck: t.ownTruck,
              fuelCost: t.ownTruck ? t.fuelCost : 0,
              hiredCost: t.ownTruck ? 0 : t.hiredCost,
              loadingFeePerBag: fixedPricing.truckLoadingFeePerBag,
              loadingFeeWaived: t.loadingFeeWaived,
              offloadingFeePerBag: fixedPricing.truckOffloadingFeePerBag,
              offloadingFeeWaived: t.offloadingFeeWaived,
            };
          }),
        },
        expenseItems: {
          create: [
            ...data.expenses.map((e) => ({
              description: e.description,
              amount: e.amount,
              amountPaid: e.paid ? e.amount : 0,
              paid: e.paid,
              paidAt: e.paid ? new Date() : null,
              paidById: e.paid ? user.id : null,
            })),
            ...buildLoadingFeeExpenses(data.driverSales, driverById),
            ...buildPackerPayExpenses(data.production, packerByName, fixedPricing.packerPricePerBag, user.id),
            ...buildTruckCostExpenses(
              data.truckDeliveries,
              truckCustomerById,
              fixedPricing.truckLoadingFeePerBag,
              fixedPricing.truckOffloadingFeePerBag
            ),
          ],
        },
      },
    });

    await logActivity(
      `${user.name} logged the daily record for ${record.date} (${pending ? "pending" : "approved"}).`,
      user.id
    );
    if (pending) {
      after(() =>
        notifyDailyRecordApprovers(
          {
            title: "New daily record awaiting approval",
            body: `${user.name} logged the record for ${record.date}.`,
            url: "/approvals",
          },
          user.id
        )
      );
    }
    revalidatePath("/", "layout");
    return { ok: true };
  } catch (e) {
    if (e instanceof Prisma.PrismaClientKnownRequestError && e.code === "P2002") {
      return { ok: false, error: `A daily record for ${data.date} already exists.` };
    }
    throw e;
  }
}

export interface UpdateDailyRecordResult {
  ok: boolean;
  error?: string;
}

async function cascadeRecalculate(
  tx: Prisma.TransactionClient,
  fromDate: string,
  startingClosingStock: number,
  startingLeakageClosing: number,
  excludeId?: string
) {
  const forward = await tx.dailyRecord.findMany({
    where: { status: "APPROVED", date: { gt: fromDate } },
    include: dailyRecordInclude,
    orderBy: { date: "asc" },
  });

  let runningClosing = startingClosingStock;
  let runningLeakageClosing = startingLeakageClosing;

  for (const rec of forward) {
    if (rec.id === excludeId) {
      // Its opening/closing were already set explicitly (e.g. a Super Admin override) —
      // don't recompute it, just carry its already-saved closing forward.
      runningClosing = rec.closingStock;
      runningLeakageClosing = rec.leakageClosing;
      continue;
    }
    const opening = runningClosing;
    const leakageOpening = runningLeakageClosing;

    const closing = computeClosingStock({
      opening,
      prodTotal: recordProdTotal(rec),
      factoryBags: rec.factoryBags,
      factoryBagsFromLeakage: rec.factoryBagsFromLeakage,
      driverBagsTotal: recordDriverBagsTotal(rec),
      driverBonusBagsTotal: recordDriverBonusBagsTotal(rec),
      truckDeliveryBagsTotal: recordTruckDeliveryBagsTotal(rec),
      truckDeliveryBonusBagsTotal: recordTruckDeliveryBonusBagsTotal(rec),
      leakageBagsNew: rec.leakageBags,
    });
    const leakageClosing = computeLeakageClosing(leakageOpening, rec.leakageBags, rec.factoryBagsFromLeakage, rec.leakageWasteBags);

    await tx.dailyRecord.update({
      where: { id: rec.id },
      data: { openingStock: opening, closingStock: closing, leakageOpening, leakageClosing },
    });

    runningClosing = closing;
    runningLeakageClosing = leakageClosing;
  }
}

export async function updateDailyRecord(id: string, input: unknown): Promise<UpdateDailyRecordResult> {
  const user = await requireUser();
  const parsed = dailyRecordEditSchema.safeParse(input);
  if (!parsed.success) {
    return { ok: false, error: parsed.error.issues[0]?.message ?? "Invalid input" };
  }
  const data = parsed.data;

  const existing = await prisma.dailyRecord.findUnique({ where: { id } });
  if (!existing) {
    return { ok: false, error: "Daily record not found." };
  }

  const canEdit = isApprover(user.role) || (existing.createdById === user.id && existing.status === "PENDING");
  if (!canEdit) {
    return { ok: false, error: "You don't have permission to edit this record." };
  }

  const dateChanged = data.date !== existing.date;
  if (dateChanged) {
    const conflict = await prisma.dailyRecord.findUnique({ where: { date: data.date } });
    if (conflict && conflict.id !== id) {
      return { ok: false, error: `A daily record for ${data.date} already exists.` };
    }
  }

  const [fixedPricing, drivers, truckCustomers, packerByName, prevApprovedForNewDate] = await Promise.all([
    getPricingSettings(),
    prisma.driver.findMany({ where: { id: { in: data.driverSales.map((d) => d.driverId) } } }),
    prisma.customer.findMany({
      where: { id: { in: data.truckDeliveries.map((t) => t.customerId) } },
    }),
    resolvePackers(
      data.production.map((p) => p.packerName),
      user.id
    ),
    dateChanged
      ? prisma.dailyRecord.findFirst({
          where: { status: "APPROVED", date: { lt: data.date }, id: { not: id } },
          orderBy: { date: "desc" },
        })
      : Promise.resolve(null),
  ]);

  const overrideApplied =
    user.role === "SUPER_ADMIN" && (data.openingStockOverride != null || data.leakageOpeningOverride != null);
  const opening =
    user.role === "SUPER_ADMIN" && data.openingStockOverride != null
      ? data.openingStockOverride
      : dateChanged
        ? (prevApprovedForNewDate?.closingStock ?? 0)
        : existing.openingStock;
  const leakageOpening =
    user.role === "SUPER_ADMIN" && data.leakageOpeningOverride != null
      ? data.leakageOpeningOverride
      : dateChanged
        ? (prevApprovedForNewDate?.leakageClosing ?? 0)
        : existing.leakageOpening;

  if (data.factoryBagsFromLeakage + data.leakageWasteBags > leakageOpening) {
    return {
      ok: false,
      error: `Only ${leakageOpening} bags are available in the leakage pile to rebag or waste.`,
    };
  }

  const prodTotal = data.production.reduce((s, p) => s + p.bags, 0);
  const driverBagsTotal = data.driverSales.reduce((s, d) => s + d.bags, 0);
  const driverBonusBagsTotal = data.driverSales.reduce((s, d) => s + d.bonusBags, 0);
  const truckDeliveryBagsTotal = data.truckDeliveries.reduce((s, t) => s + t.bags, 0);
  const truckDeliveryBonusBagsTotal = data.truckDeliveries.reduce((s, t) => s + t.bonusBags, 0);

  const closing = computeClosingStock({
    opening,
    prodTotal,
    factoryBags: data.factoryBags,
    factoryBagsFromLeakage: data.factoryBagsFromLeakage,
    driverBagsTotal,
    driverBonusBagsTotal,
    truckDeliveryBagsTotal,
    truckDeliveryBonusBagsTotal,
    leakageBagsNew: data.leakageBags,
  });
  const leakageClosing = computeLeakageClosing(
    leakageOpening,
    data.leakageBags,
    data.factoryBagsFromLeakage,
    data.leakageWasteBags
  );

  const canEditFactoryPrice = user.role === "ADMIN" || user.role === "SUPER_ADMIN";
  const factoryPricePerBag = canEditFactoryPrice ? data.factoryPricePerBag : fixedPricing.factoryPricePerBag;
  const driverById = new Map(drivers.map((d) => [d.id, d]));
  const truckCustomerById = new Map(truckCustomers.map((c) => [c.id, c]));

  try {
    await prisma.$transaction(
      async (tx) => {
        await tx.productionLine.deleteMany({ where: { dailyRecordId: id } });
        await tx.driverSale.deleteMany({ where: { dailyRecordId: id } });
        await tx.truckDelivery.deleteMany({ where: { dailyRecordId: id } });
        await tx.expenseItem.deleteMany({ where: { dailyRecordId: id } });

        await tx.dailyRecord.update({
          where: { id },
          data: {
            date: data.date,
            openingStock: opening,
            closingStock: closing,
            factoryBags: data.factoryBags,
            factoryBagsFromLeakage: data.factoryBagsFromLeakage,
            factoryPricePerBag,
            factoryCustomerId: data.factoryCustomerId || null,
            pumpWaterAmount: data.pumpWaterAmount,
            leakageOpening,
            leakageBags: data.leakageBags,
            leakageWasteBags: data.leakageWasteBags,
            leakageClosing,
            productionLines: {
              create: data.production.map((p) => {
                const packer = packerByName.get(p.packerName.trim().toLowerCase());
                return { packerId: packer!.id, bags: p.bags, pricePerBag: fixedPricing.packerPricePerBag };
              }),
            },
            driverSales: {
              create: data.driverSales.map((d) => {
                const driver = driverById.get(d.driverId);
                return {
                  driverId: d.driverId,
                  bags: d.bags,
                  pricePerBag: driver?.pricePerBag ?? 0,
                  loadingFee: driver?.loadingFee ?? 0,
                  loadingFeeWaived: d.loadingFeeWaived,
                  bonusBags: d.bonusBags,
                };
              }),
            },
            truckDeliveries: {
              create: data.truckDeliveries.map((t) => {
                const customer = truckCustomerById.get(t.customerId);
                return {
                  customerId: t.customerId,
                  bags: t.bags,
                  bonusBags: t.bonusBags,
                  pricePerBag: customer?.pricePerBag ?? 0,
                  ownTruck: t.ownTruck,
                  fuelCost: t.ownTruck ? t.fuelCost : 0,
                  hiredCost: t.ownTruck ? 0 : t.hiredCost,
                  loadingFeePerBag: fixedPricing.truckLoadingFeePerBag,
                  loadingFeeWaived: t.loadingFeeWaived,
                  offloadingFeePerBag: fixedPricing.truckOffloadingFeePerBag,
                  offloadingFeeWaived: t.offloadingFeeWaived,
                };
              }),
            },
            expenseItems: {
              create: [
                ...data.expenses.map((e) => ({
                  description: e.description,
                  amount: e.amount,
                  amountPaid: e.paid ? e.amount : 0,
                  paid: e.paid,
                  paidAt: e.paid ? new Date() : null,
                  paidById: e.paid ? user.id : null,
                })),
                ...buildLoadingFeeExpenses(data.driverSales, driverById),
                ...buildPackerPayExpenses(data.production, packerByName, fixedPricing.packerPricePerBag, user.id),
                ...buildTruckCostExpenses(
                  data.truckDeliveries,
                  truckCustomerById,
                  fixedPricing.truckLoadingFeePerBag,
                  fixedPricing.truckOffloadingFeePerBag
                ),
              ],
            },
          },
        });

        if (existing.status === "APPROVED") {
          if (dateChanged) {
            const boundaryDate = existing.date < data.date ? existing.date : data.date;
            const anchor = await tx.dailyRecord.findFirst({
              where: { status: "APPROVED", date: { lt: boundaryDate }, id: { not: id } },
              orderBy: { date: "desc" },
            });
            await cascadeRecalculate(
              tx,
              anchor?.date ?? "",
              anchor?.closingStock ?? 0,
              anchor?.leakageClosing ?? 0,
              overrideApplied ? id : undefined
            );
          } else {
            await cascadeRecalculate(tx, existing.date, closing, leakageClosing);
          }
        }
      },
      { timeout: 20000 }
    );
  } catch (e) {
    if (e instanceof Prisma.PrismaClientKnownRequestError && e.code === "P2002") {
      return { ok: false, error: `A daily record for ${data.date} already exists.` };
    }
    throw e;
  }

  await logActivity(
    dateChanged
      ? `${user.name} edited the daily record and moved its date from ${existing.date} to ${data.date}.`
      : `${user.name} edited the daily record for ${existing.date}.`,
    user.id
  );
  if (user.id !== existing.createdById) {
    after(() =>
      sendPushToUsers([existing.createdById], {
        title: "Your daily record was updated",
        body: `${user.name} made changes to your daily record for ${data.date}.`,
        url: "/daily-record",
      })
    );
  }
  revalidatePath("/", "layout");
  return { ok: true };
}

export interface DeleteDailyRecordResult {
  ok: boolean;
  error?: string;
}

export async function deleteDailyRecord(id: string): Promise<DeleteDailyRecordResult> {
  const user = await requireRole(["ADMIN", "SUPER_ADMIN"]);

  const existing = await prisma.dailyRecord.findUnique({ where: { id } });
  if (!existing) {
    return { ok: false, error: "Daily record not found." };
  }

  await prisma.$transaction(
    async (tx) => {
      if (existing.status === "APPROVED") {
        const prev = await tx.dailyRecord.findFirst({
          where: { status: "APPROVED", date: { lt: existing.date } },
          orderBy: { date: "desc" },
        });
        const startingClosing = prev?.closingStock ?? 0;
        const startingLeakageClosing = prev?.leakageClosing ?? 0;

        await tx.dailyRecord.delete({ where: { id } });
        await cascadeRecalculate(tx, existing.date, startingClosing, startingLeakageClosing);
      } else {
        await tx.dailyRecord.delete({ where: { id } });
      }
    },
    { timeout: 20000 }
  );

  await logActivity(`${user.name} deleted the daily record for ${existing.date}.`, user.id);
  revalidatePath("/", "layout");
  return { ok: true };
}

export interface DailyRecordFormData {
  id: string;
  date: string;
  openingStock: number;
  leakageOpening: number;
  production: { packerName: string; bags: number; paid: boolean }[];
  factoryBags: number;
  factoryBagsFromLeakage: number;
  factoryPricePerBag: number;
  factoryCustomerId: string | null;
  pumpWaterAmount: number;
  driverSales: { driverId: string; bags: number; bonusBags: number; loadingFeeWaived: boolean }[];
  truckDeliveries: {
    customerId: string | null;
    bags: number;
    bonusBags: number;
    ownTruck: boolean;
    fuelCost: number;
    hiredCost: number;
    loadingFeeWaived: boolean;
    offloadingFeeWaived: boolean;
  }[];
  leakageBags: number;
  leakageWasteBags: number;
  expenses: { description: string; amount: number; paid: boolean }[];
}

/**
 * Used by the daily-record form to auto-fill when a picked date already has
 * a record — e.g. one started via the Total Produced page's quick-add.
 */
export async function findDailyRecordByDate(date: string): Promise<DailyRecordFormData | null> {
  await requireUser();
  if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) return null;

  const record = await prisma.dailyRecord.findUnique({ where: { date }, include: dailyRecordInclude });
  if (!record) return null;

  const packerPaid = packerPaidMap(record.expenseItems);

  return {
    id: record.id,
    date: record.date,
    openingStock: record.openingStock,
    leakageOpening: record.leakageOpening,
    production: record.productionLines.map((p) => ({
      packerName: p.packer.name,
      bags: p.bags,
      paid: packerPaid.get(p.packerId) ?? false,
    })),
    factoryBags: record.factoryBags,
    factoryBagsFromLeakage: record.factoryBagsFromLeakage,
    factoryPricePerBag: record.factoryPricePerBag,
    factoryCustomerId: record.factoryCustomerId,
    pumpWaterAmount: record.pumpWaterAmount,
    driverSales: record.driverSales.map((d) => ({
      driverId: d.driverId,
      bags: d.bags,
      bonusBags: d.bonusBags,
      loadingFeeWaived: d.loadingFeeWaived,
    })),
    truckDeliveries: record.truckDeliveries.map((t) => ({
      customerId: t.customerId,
      bags: t.bags,
      bonusBags: t.bonusBags,
      ownTruck: t.ownTruck,
      fuelCost: t.fuelCost,
      hiredCost: t.hiredCost,
      loadingFeeWaived: t.loadingFeeWaived,
      offloadingFeeWaived: t.offloadingFeeWaived,
    })),
    leakageBags: record.leakageBags,
    leakageWasteBags: record.leakageWasteBags,
    expenses: record.expenseItems
      .filter((e) => !isAutoGeneratedExpense(e.description))
      .map((e) => ({ description: e.description, amount: e.amount, paid: e.paid })),
  };
}

export interface AddProductionResult {
  ok: boolean;
  error?: string;
}

/**
 * Quick-add from the Total Produced page. If the date has no record yet,
 * creates a minimal one (production only, everything else defaulted) via
 * the normal create path. If a record already exists, appends to its
 * production and re-saves via the normal update path — reusing both so
 * stock recalculation, approval status, and permission checks all stay
 * exactly as correct as they are for the full form.
 */
export async function addProductionForDate(
  date: string,
  newProduction: { packerName: string; bags: number }[]
): Promise<AddProductionResult> {
  await requireUser();
  if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) {
    return { ok: false, error: "Invalid date" };
  }
  const cleaned = newProduction
    .map((p) => ({ packerName: p.packerName.trim(), bags: p.bags }))
    .filter((p) => p.packerName && p.bags > 0);
  if (cleaned.length === 0) {
    return { ok: false, error: "Add at least one packer with bags." };
  }

  const existing = await prisma.dailyRecord.findUnique({ where: { date }, include: dailyRecordInclude });

  if (!existing) {
    return createDailyRecord({
      date,
      openingStockOverride: null,
      leakageOpeningOverride: null,
      production: cleaned,
      factoryBags: 0,
      factoryBagsFromLeakage: 0,
      factoryPricePerBag: 0,
      factoryCustomerId: null,
      pumpWaterAmount: 0,
      driverSales: [],
      truckDeliveries: [],
      leakageBags: 0,
      leakageWasteBags: 0,
      expenses: [],
    });
  }

  const packerPaid = packerPaidMap(existing.expenseItems);
  const combinedProduction = [
    ...existing.productionLines.map((p) => ({
      packerName: p.packer.name,
      bags: p.bags,
      paid: packerPaid.get(p.packerId) ?? false,
    })),
    ...cleaned.map((p) => ({ ...p, paid: false })),
  ];
  return updateDailyRecord(existing.id, {
    date: existing.date,
    openingStockOverride: null,
    leakageOpeningOverride: null,
    production: combinedProduction,
    factoryBags: existing.factoryBags,
    factoryBagsFromLeakage: existing.factoryBagsFromLeakage,
    factoryPricePerBag: existing.factoryPricePerBag,
    factoryCustomerId: existing.factoryCustomerId,
    pumpWaterAmount: existing.pumpWaterAmount,
    driverSales: existing.driverSales.map((d) => ({
      driverId: d.driverId,
      bags: d.bags,
      bonusBags: d.bonusBags,
      loadingFeeWaived: d.loadingFeeWaived,
    })),
    truckDeliveries: existing.truckDeliveries.map((t) => ({
      customerId: t.customerId,
      bags: t.bags,
      bonusBags: t.bonusBags,
      ownTruck: t.ownTruck,
      fuelCost: t.fuelCost,
      hiredCost: t.hiredCost,
      loadingFeeWaived: t.loadingFeeWaived,
      offloadingFeeWaived: t.offloadingFeeWaived,
    })),
    leakageBags: existing.leakageBags,
    leakageWasteBags: existing.leakageWasteBags,
    expenses: existing.expenseItems
      .filter((e) => !isAutoGeneratedExpense(e.description))
      .map((e) => ({ description: e.description, amount: e.amount, paid: e.paid })),
  });
}
