"use client";

import { useState } from "react";
import DailyRecordFormModal, { type DailyRecordFormInitial } from "./DailyRecordFormModal";
import { isAutoGeneratedExpense, packerPaidMap, type DailyRecordFull } from "@/lib/records";

interface DriverOption {
  id: string;
  name: string;
  pricePerBag: number;
  loadingFee: number;
}
interface CustomerOption {
  id: string;
  name: string;
  pricePerBag: number;
}
export default function EditDailyRecordButton({
  record,
  drivers,
  customers,
  canEditOpeningStock,
  canEditFactoryPrice,
  canEditLeakageOpening,
  packerPricePerBag,
}: {
  record: DailyRecordFull;
  drivers: DriverOption[];
  customers: CustomerOption[];
  canEditOpeningStock?: boolean;
  canEditFactoryPrice?: boolean;
  canEditLeakageOpening?: boolean;
  packerPricePerBag: number;
}) {
  const [open, setOpen] = useState(false);

  const packerPaid = packerPaidMap(record.expenseItems);
  const initial: DailyRecordFormInitial = {
    date: record.date,
    openingStock: record.openingStock,
    production: record.productionLines.map((p) => ({
      packerName: p.packer.name,
      bags: p.bags,
      paid: packerPaid.get(p.packerId) ?? false,
    })),
    factoryBags: record.factoryBags,
    factoryBagsFromLeakage: record.factoryBagsFromLeakage,
    factoryPricePerBag: record.factoryPricePerBag,
    factoryCustomerId: record.factoryCustomerId,
    pumpWaterAmount: record.pumpWaterAmount,
    driverSales: record.driverSales.map((d) => ({
      driverId: d.driverId,
      bags: d.bags,
      bonusBags: d.bonusBags,
      loadingFeeWaived: d.loadingFeeWaived,
    })),
    truckDeliveries: record.truckDeliveries.map((t) => ({
      customerId: t.customerId,
      bags: t.bags,
      bonusBags: t.bonusBags,
      ownTruck: t.ownTruck,
      fuelCost: t.fuelCost,
      hiredCost: t.hiredCost,
    })),
    leakageBags: record.leakageBags,
    leakageWasteBags: record.leakageWasteBags,
    expenses: record.expenseItems
      .filter((e) => !isAutoGeneratedExpense(e.description))
      .map((e) => ({ description: e.description, amount: e.amount, paid: e.paid })),
  };

  return (
    <>
      <button className="icon-btn no-print" title="Edit this record" onClick={() => setOpen(true)}>
        ✎
      </button>
      {open && (
        <DailyRecordFormModal
          mode="edit"
          recordId={record.id}
          open={open}
          onClose={() => setOpen(false)}
          initial={initial}
          leakageOpening={record.leakageOpening}
          drivers={drivers}
          customers={customers}
          canEditOpeningStock={canEditOpeningStock}
          canEditFactoryPrice={canEditFactoryPrice}
          canEditLeakageOpening={canEditLeakageOpening}
          packerPricePerBag={packerPricePerBag}
        />
      )}
    </>
  );
}
